### ISSUE TITLE
all downloads should use dod.download()

### ISSUE THREAD

**Issue by dankelley** [AnnieHow/dod#19]
As shown below, there are several instances of direct calls to `download.file()`.  These should all be changed to use `dod.download()` so that we get uniform error checking, etc.  (Note the `git` command I'm using ... this is a very helfull method for finding things in code.)

<img width="751" alt="Screenshot 2022-10-11 at 12 36 27 PM" src="https://user-images.githubusercontent.com/99469/195136253-a9d138e5-e737-4656-b279-db36d3cff0bf.png">

**Comment by AnnieHow** [comment]
This was fixed in commit e104cacf5ba3b3eec711db6ed33f6b47efdd7b00.
