### ISSUE TITLE
two package-level things to fix (video)

### ISSUE THREAD

**Issue by dankelley** [AnnieHow/dod#20]
Hi.  No time to type -- please see the video

https://user-images.githubusercontent.com/99469/195349517-0d26e1af-8463-4d65-80a7-f058f8b7c00b.mp4

**Comment by AnnieHow** [comment]
Lazy data removed in commit 7c420a7ded70396f0fa360f5c946151cb72adda4. 

When I add `rmarkdown` as an import in NAMESPACE it automatically removes it so still figuring this one out.

**Comment by AnnieHow** [comment]
Potential fix for the second error in commit dbd7088090a6b28dd730d29fcc1d4a4b4e9d7ef4. 

We added in `rmarkdown` as a Depends ourselves, might not be necessary there and get no errors in Check once removed. Let me know if it is and I can go back to the drawing board on this!
