### ISSUE TITLE
dod.ctd(program-"BATS") producing error

### ISSUE THREAD

**Issue by j-harbin** [AnnieHow/dod#23]
Hi All,

I'm just working on getting familiar with the package. I did the following and receive an error (see reprex below). Any idea what I'm doing wrong?

``` r
library(oce)
#> Loading required package: gsw
library(dod)
destdir <- "~/data/ctd"
b <- dod.ctd(program="BATS", destdir=destdir)
#> Error in FUN(X[[i]], ...): cannot coerce type 'closure' to vector of type 'character'
```

<sup>Created on 2022-10-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
Um, I don't get that error.  If there is no directory called `~/data/ctd` I get
```R
Error in dod.download(url, ID, destdir = destdir, debug = debug) :
  destdir "~/data/ctd" does not exist; please create it first.   
```
which is what we want.

And if the directory *does* exist, I get
```
Error in dod.download(url, ID, destdir = destdir, debug = debug) :
  Unable to download "http://batsftp.bios.edu/BATS/ctd/ASCII/b_ctd.txt" to "" 
```
which is something our code should catch, I think.

But I don't get your error.  I wonder whether @AnnieHow does?

PS. I won't likely see email again for a while, with other things going on right now.

**Comment by AnnieHow** [comment]
When there's no directory I got the same help message as Dan. When I do have the directory I'm calling for I got your error @j-harbin. 

When I have the directory and add `debug=1` , I get the error below. 
<img width="789" alt="Screen Shot 2022-10-25 at 9 49 51 AM" src="https://user-images.githubusercontent.com/105868454/197792178-d01335de-67ec-4875-9e9b-c72d6293b302.png">
Maybe the error is in `download.R` line 34.

**Comment by dankelley** [comment]
Low priority but possibly useful -- with "main" commit 20a7529c04aa1ce2aea4c1cf8ad7df4da624220e I get as below, i.e. I don't know how to get an index.  (I don't actually need BATS data right now, but I figured I'd try this to see.  I didn't even read the docs ... I'm just kind of guessing that setting `index` to TRUE would download something.)

``` r
library(oce)
#> Loading required package: gsw
library(dod)
destdir <- "~/data/ctd"
b <- dod.ctd(program="BATS", destdir=destdir, index=TRUE)
#> Error in if (is.null(ID) | ID < 10000) stop("Must provide an ID number greater than 10000"): argument is of length zero
```

<sup>Created on 2022-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
