### ISSUE TITLE
Make file argument optional for dod.ctd

### ISSUE THREAD

**Issue by j-harbin** [AnnieHow/dod#29]

**Comment by j-harbin** [comment]
Fixed with AH in Z (commit d8689bb39c662115bca5124ea0acefe6aa54c64e) . We did the following:

1. Removed the stop messages if file argument was NULL
2. If file was NULL, we defined it for BBMP  if `index=TRUE` and `index=FALSE`
3. Redefined the url argument in ctd.R to not involve the file argument

We will now be working on BATS.

**Comment by AnnieHow** [comment]
For BATS, JH and I did Steps 1 and 2, 3 had already been coded for. Fixed in commit 63ebd9aefc4ed4bda54424e4567e95515d385905.
