### ISSUE TITLE
Proposal: Rearrange code for exercise in dod.ctd() document

### ISSUE THREAD

**Issue by j-harbin** [AnnieHow/dod#30]
Right now if the user types `?dod.ctd`, the example provided says the following:

```
destdir <- "~/data/ctd"
i <- dod.ctd("BBMP", year=2022, index=TRUE, file="index.txt")
f <- dod.ctd("BBMP", year=2022, ID=i$file[1], destdir=destdir, file="bbmp.txt")
library(oce)
ctd <- read.ctd(f)
plot(ctd)
```

Just because I'm picky, I like having the `library(oce)` command at the top of the code.

**Comment by AnnieHow** [comment]
Fixed in Z with JH in commit 68453f58e39e92ea2c0a750951949f70c5bfbcf9.
