### ISSUE TITLE
Finalize what dod.ctd() should return

### ISSUE THREAD

**Issue by j-harbin** [AnnieHow/dod#31]
Right now, in the documentation for `dod.ctd()`, we say that the return value is "If index is TRUE, and program is "BBMP" or "BATS", return a data frame. Otherwise, return the name of the downloaded file.". 

This is true for when `program = "BBMP"`, because when `index=FALSE`,  `oce` has the ability to read the produced name of the downloaded file. See below

```
library(oce)
destdir <- "~/data/ctd"
i <- dod.ctd("BBMP", year=2022, index=TRUE, file="index.txt")
f <- dod.ctd("BBMP", year=2022, ID=i$file[1], destdir=destdir, file="bbmp.txt")
ctd <- read.ctd(f)
```

This  becomes problematic, however,  when `program = "BATS"` and `index=FALSE`. If we do as the documentation says, and simply return a downloaded file, `oce` does not know how to read the contents of the file. This means, the only way the user can read this file is if they know what the column names are. See below, for example, assuming "f" is the downloaded file name.
```
 namesInfo <- c("ID", "dateDeployed","dateRecovered","decimalDateDeployed","decimalDateRecovered",
                "decimalDayDeployed", "timeDeployed", "timeRecovered", "latitudeDeployed", "latitudeRecovered",
                "longitudeDeployed", "longitudeRecovered")
            t <- read.csv(f, sep="\t", header=FALSE, col.names= namesInfo)
```

They only know what the column names are if they go to the BATS index website. If we are requiring the users to go to the BATS website, this is defeating the purpose of the package. I therefore propose if `program="BATS"` and `index=FALSE`, a data frame file should be returned (PS- this is currently what's coded in, but the documentation has not been updated to represent this).

**Comment by dankelley** [comment]
Can you put a reprex here?  (Use the `reprex` package.) so I can see what's in those files?

PS. I don't think the purpose is necessarily to produce files that oce can read.  There's lots of great oceanographic data that oce cannot read.  Every few months, a user makes the case that some data format is worth reading, and oce gets extended to handle it.  That might happen for BATS ... but I'd like to see a file first and also a documentation on the BATS website for the file format. Oce doesn't attempt to handle data types that are uncommon, or undocumented; it's better to let the user, who has an interest in the data, figure out things like whether temperature is measured on the modern scale, the one before that, or the one before that :-)

**Comment by j-harbin** [comment]
Of course! For "BBMP":

``` r
library(oce)
#> Loading required package: gsw
library(dod)
destdir <- "~/data/ctd"
i <- dod.ctd("BBMP", year=2022, index=TRUE, file="index.txt")
#> 2022667ODFSUMMARY.tsv
#> ./2022667ODFSUMMARY.tsv
f <- dod.ctd("BBMP", year=2022, ID=i$file[1], destdir=destdir, file="bbmp.txt")
ctd <- read.ctd(f)
ctd
#> ctd object has data as follows.
#>    time [1:142]: 2022-01-07 12:18:48, 2022-01-07 12:18:50, ..., 2022-01-07 12:20:23, 2022-01-07 12:20:26
#>    scan [1:142]: 4185, 4221, ..., 5698, 5752
#>    pressure [1:142]: 1.0, 1.5, ..., 71.0, 71.5
#>    temperature [1:142]: 5.1020, 5.1551, ..., 5.6340, 5.6386
#>    conductivity [1:142]: 0.65367, 0.65579, ..., 0.71431, 0.71437
#>    oxygenVoltage [1:142]: 3.0174, 3.0185, ..., 0.5362, 0.5338
#>    fluorescence [1:142]: 0.6261, 0.6662, ..., 0, 0
#>    PSAR [1:142]: 2.6422, 2.0195, ..., 0e+00, 1e-05
#>    pH [1:142]: 7.938, 7.937, ..., 7.462, 7.389
#>    salinity [1:142]: 28.716, 28.773, ..., 31.138, 31.137
#>    theta [1:142]: 5.1019, 5.1550, ..., 5.6286, 5.6332
#>    sigmaTheta [1:142]: 22.687, 22.727, ..., 24.546, 24.544
#>    oxygen [1:142]: 6.5108, 6.5019, ..., 0.0881, 0.0884
#>    scan2 [1:142]: 64, 17, ..., 13, 61
```

<sup>Created on 2022-10-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

For BATS, the `reprex` won't work because I am downloading a file, but I'll produce the output from the following code:

```
library(oce)
t <- dod.ctd(program="BATS", file="bats.txt", ID=10001)
head(t)
```

```
      ID     date latitude longitude pressure depth temperature conductivity salinity oxygen
1 10001001 1988.803   31.783    64.116        4   4.0      25.708       5.5729   36.407 205.99
2 10001001 1988.803   31.783    64.116        6   6.0      25.711       5.5734   36.407 207.11
3 10001001 1988.803   31.783    64.116        8   7.9      25.710       5.5736   36.409 207.69
4 10001001 1988.803   31.783    64.116       10   9.9      25.715       5.5741   36.408 207.74
5 10001001 1988.803   31.783    64.116       12  11.9      25.715       5.5742   36.408 208.31
6 10001001 1988.803   31.783    64.116       14  13.9      25.714       5.5742   36.408 207.83
  beamAttenuationCoefficient fluorescence  PAR
1                      0.438         -999 -999
2                      0.438         -999 -999
3                      0.438         -999 -999
4                      0.438         -999 -999
5                      0.438         -999 -999
6                      0.438         -999 -999
```

**Comment by j-harbin** [comment]
After a chat with @dankelley , we decided there are two possibilities:

1. Produce a file name and then show the user in a vignette how to read the file.
2. Have an additional argument named read, and if it's true we will read the csv.

@AnnieHow and I will work on this together.

**Comment by dankelley** [comment]
One thing -- if we read the data it will be important to document the assumptions being made, e.g. on the unit of conductivity and oxygen for BATS.  I imagine there is a document on the BATS site that explains this, and a link ought to go in the documentation for this.

As J and I discussed, users get confused by lengthy output from `?dod.ctd` and so I think the place to document things like the format of the `bbmp` and `bats` indices is in a vignette.

**Comment by j-harbin** [comment]
This was fixed in commit 923fde37caa575293b564852507ef1c430ef7033 and commit 32e87f5542ac23c1b256a7d78a385787434f7efe of main for CTD BBMP and BATS. A read argument was added.

For BATS:
If read is FALSE, a downloaded file is returned. If read is TRUE a data frame is returned.

For BBMP:
If read is FALSE, a downloaded file is returned. If read is TRUE and index is TRUE a data frame is returned. If read is TRUE and index is FALSE an oce object is returned.

I'll keep this open to make sure the other functions are consistent.

**Comment by dankelley** [comment]
I'm not actually convinced that adding a `read` argument to `dod` functions is sensible.  Please note that most `oce::read`` functions have a *lot* of arguments, and the default method is not always the right approach.  I worry that having `dod` call a default `oce::read` function will make users think that this is the best approach.  But it can lead to a world of problems.  After all, those extra arguments are there for a reason: different data flavours require different arguments, and different applications do also.

Comments, @j-harbin and @AnnieHow ?

**Comment by j-harbin** [comment]
@AnnieHow and I have chatted about this in great detail a few months ago. I think it's *very* important to not only download a file and that be the end of it for the following reasons:

**Argument One**
Let's use BATS as an example. Let's say I wanted to analyze data from ID 10001, year 2000:


```
library(dod)
library(oce)
t <- dod.ctd.bats(year=2000, index=FALSE, ID=10001, read=TRUE)
names(t)

 [1] "ID"                         "date"                      
 [3] "latitude"                   "longitude"                 
 [5] "pressure"                   "depth"                     
 [7] "temperature"                "conductivity"              
 [9] "salinity"                   "oxygen"                    
[11] "beamAttenuationCoefficient" "fluorescence"              
[13] "PAR"  
```

If we did not have the read function, and simply downloaded the file, the user would be required to go to the BATS website to determine what each column in the data frame is. In my opinion, this defeats the purpose of the package if the user is still required to locate the index to determine what each column is.

**Argument Two**
When I think of `dod.topo()` in the `oce` package, it produces a downloaded file. Well, without the use of `read.topo()` (unless you are an expert with topography data) this file is essentially useless. With `read.topo()`, `oce` does not suggest this is the *best* way to read this data, but rather this is *a* way to read this data. If the user has another idea in mind, they still have the downloaded file to do what they want with.

**Argument Three** (Because Dan likes lists of three :) )

When I think of `argoFloats` package, in my opinion, one of the selling features of this is `readProfiles()`. Without this, `argoFloats` would simply only provide you a list of files. How would the user then know what to do with it? Reading the profiles allows the user to further their analysis.

In my opinion, not reading the data for the user means the job is only half finished.

**Comment by dankelley** [comment]
What if e.g. the docs for `dod.topo()` described the returned value in more detail, e.g. changing
```
#' @return String indicating the full pathname to the downloaded file.
```
to
```
#' @return String indicating the full pathname to the downloaded file. This may be read with `oce::read.topo()`.
```

**Comment by dankelley** [comment]
After a Z call, JH and DK agreed that the original intention of adding the `read` argument can be handled by documenting how to deal with the downloaded files.

On the question "should some dod functions get a `read` argument", the votes (on -1 to +1 scale) were
* DK: -0.5
* JH: -0.000001

I tried some sample wording during the Z call, and it seemed relatively sensible. Therefore, J and I agreed that I do a bit more work on this over the holiday.  I don't think any users will be harmed by this, since it is early days for this package and it's not on CRAN yet.

**Comment by dankelley** [comment]
I'm recoding, with `read` removed.  In the example, I see as follows.  I think that filename ought to be more specific.  The tsv just means tab-separated-values (like csv for comma-separated-values) and so the filename just says that it's an index.  I think the name ought to be something like `index_bbmp_2022.tsv` because then the first word tells us basically what it is, the second tells us the program, and the third tells the year.  I'll go ahead and do this change -- it can always be undone and we don't want to wait for votes on all aspects.
```R
> indexFile <- dod.ctd("BBMP", year=2022, index=TRUE, file="index")
> 
> indexFile
[1] "./index.tsv"
```

**Comment by dankelley** [comment]
Oh, sorry.  I see that we are getting that name because we specified it in the call.  I'll change the call in the example.

**Comment by dankelley** [comment]
I'm done with bbmp and am looking at bats now.  I see that the first param, `year`, is not used in the code.  We should not have unused params, so I will delete this.  It's ok that the "children" of `dod.ctd()` have different params ... datasets are simply not all alike.

**Comment by dankelley** [comment]
Hm.  The param `index` should really be named `info`,  because it is not an index in the normal use of that word.  Also, on the server, it is called an info file (e.g. data in http://batsftp.bios.edu/BATS/ctd/ASCII/b10001_ctd.txt, information about sampling place/time in http://batsftp.bios.edu/BATS/ctd/ASCII/b10001_info.txt).

I will change this.

**Comment by dankelley** [comment]
Oh, my.  I see that recent BATS files have extra letters where the others just have numbers. I guess that's ok but I don't know how the user would be aware of that.

I will solve this by improving the number-check on ID and also by providing the source link in the docs.

<img width="1167" alt="Screenshot 2022-12-22 at 2 55 10 PM" src="https://user-images.githubusercontent.com/99469/209206969-4be9cd33-af2e-47b2-878b-20c6b3b67702.png">

**Comment by dankelley** [comment]
Re the `_QC` in some filenames., this is a bit of a problem because of how URLs are constructed in `dod.ctd.bats()`.  I think a reasonable approach for e.g. ID=50056 would be first to try
http://batsftp.bios.edu/BATS/ctd/ASCII/b50056_ctd.txt and if that fails, try http://batsftp.bios.edu/BATS/ctd/ASCII/b50056_QC_ctd.txt

I'm basically just guessing here.  In the new year, perhaps somebody who is actually using these data will think about this.  (What a useless server this is, with no index files.)

**Comment by dankelley** [comment]
I updated `dod.ctd.bats()`.  Wow, those data need a lot of work.  But all a user has to do is to copy/paste the help file to work with another ID.  And, while they are at it, they might happen to know the units of oxygen, etc., which are not listed in the file.

**Comment by dankelley** [comment]
I am closing this issue because it (as described by its title) has been addressed.
