### ISSUE TITLE
Typo in dodDebug help packages

### ISSUE THREAD

**Issue by j-harbin** [AnnieHow/dod#33]
See the following:

![Screen Shot 2022-11-01 at 11 06 04 AM](https://user-images.githubusercontent.com/58750538/199252477-e4021f1c-0c10-45aa-be56-e317afec0ee5.png)

**Comment by AnnieHow** [comment]
Fixed on Z with JH in commit ba4d3f131351b5225b9a4cb208d22ce72f65b4c8.
