### ISSUE TITLE
dod.ctd("bbmp",index=TRUE) should default year to the present one

### ISSUE THREAD

**Issue by dankelley** [AnnieHow/dod#39]
As shown below, presently we must give the year. But it's easy to compute the year if not given. @AnnieHow, if you agree that `dod.ctd()` ought to default the year if not given, perhaps you can recode it.

```R
> library(dod)
> i <- dod.ctd("BBMP", index=TRUE)
Error in dod.ctd.bbmp(...) : must give 'year'
> gsub("-.*","",Sys.Date())
[1] "2022"
```

**Comment by AnnieHow** [comment]
After discussion with @j-harbin we've decided to leave the year without a default. We want the function to stop the user when a year is not provided so they know from the jump that they can select for the year they're interested in rather than having to check the arguments in the help page.
