### ISSUE TITLE
why does dod.ctd() rename files?

### ISSUE THREAD

**Issue by dankelley** [AnnieHow/dod#40]
Please see below.  I think it ought to download to the original name, as in the index. However, it is renaming it, and even changing the suffix (which means that `oce::read.oce()` cannot guess what the file contains).

@AnnieHow can you change this, so it saves the file with the original name?

```R
> library(dod)
> i <- dod.ctd("BBMP", year="2022", index=TRUE)
> i$file[1]
[1] "D22667001.ODF"
> f <- dod.ctd("BBMP", year="2022", ID=i$file[1])
> f
[1] "./2022D22667001.txt"
```

**Comment by AnnieHow** [comment]
This should be fixed for `dod.ctd.bbmp` in commit 4c168b5c414651b85599916540d986e19e8bb62e. Going to take a look at what the file names are for `dod.ctd.gtspp` and `dod.ctd.bats`.

**Comment by AnnieHow** [comment]
@dankelley that file name is the file name from the original index- is there a different file name we want to use?

**Comment by AnnieHow** [comment]
Last test suite to check these issues added in commit ad600521a568ad8893932d49b60e2d682aec4a76.
