### ISSUE TITLE
download atmospheric sounding data?

### ISSUE THREAD

**Issue by dankelley** [AnnieHow/dod#44]
I saw some interesting clouds today, which seemed to be just in a thin layer, not spread out with height.  So I thought I'd try to find some atmospheric sounding data, to see if there was a sharp variation of anything at a somewhat low level.

I ended up writing my function as `dod.sounding` (see below).

Q for @AnnieHow and @j-harbin: do you think I ought to add this to this package?  It's not exactly oceanographic, but the atmosphere and the ocean are not exactly unrelated.

PS 1. yup, there was something odd going on at a certain level -- look at the wind direction and mixing ratio, about 1000 metres up from the ground.

PS 2. This station is at Shearwater.  There are a bunch of stations all around the world that release weather balloons at 12:00 UTC.

<details>

**code**

```R
# url <- "https://weather.uwyo.edu/cgi-bin/sounding?region=naconf&TYPE=TEXT%3ALIST&YEAR=2023&MONTH=01&FROM=0812&TO=0812&STNM=73110"


dod.sounding <- function(station="73110", year, month, day, region="naconf")
{
    ymd <- strsplit(format(Sys.Date()), "-")[[1]]
    if (missing(year)) year <- ymd[1]
    if (missing(month)) month <- ymd[2]
    if (missing(day)) day <- ymd[3]
    from <- paste0(day, "12")
    to <- from
    base <- "https://weather.uwyo.edu/cgi-bin/sounding"
    url <- sprintf("%s?region=%s&TYPE=TEXT%%3ALIST&YEAR=%s&MONTH=%s&FROM=%s&TO=%s&STNM=%s",
        base, region, year, month, from, to, station)
    message(url)
    file <- paste0("sounding", "_", station, "_", year, "_", month, ".dat")
    message(file)
    ok <- download.file(url, file)
    if (ok) {
        stop("cannot download ", url)
    }
    file
}

# Download
station <- "73110"
year <- "2023"
month <- "01"
day <- "08"
file <- dod.sounding(station, year=year, month=month, day=day)

# Read
lines <- readLines(file)
start <- grep("<PRE>", lines)[1]
end <- grep("</PRE>", lines)[1]
table <- lines[seq(start+5, end-1)]
col.names <- strsplit(gsub("^ [ ]*", "", lines[start+2]), "[ ]+")[[1]]
data <- read.table(text=table, col.names=col.names)

# Plot
if (!interactive()) png("atm_%d.png", unit="in", width=7, height=7, res=200)
par(mar=c(3.3, 3.3, 1, 1), mgp=c(2, 0.7, 0), mfrow=c(2, 3))
p <- function(var, name, y)
{
    if (y == "PRES") {
        plot(data[[var]], data[[y]], type="l", cex=0.5, pch=20, col=4,
            ylab="Pressure [mbar]", xlab=name, ylim=rev(range(data[[y]])))
    } else {
        plot(data[[var]], data[[y]], type="l", cex=0.5, pch=20, col=4,
            ylab="Height [m]", xlab=name)
    }
    grid(col="gray")
}

for (y in c("HGHT", "PRES")) {
    p("TEMP", "Temperature [C]", y)
    mtext(paste0("Stn ", station, " (", year, "-", month, "-", day, " 12:00 UTC)"), cex=par("cex"))
    p("RELH", "Rel. Humidity [%]", y)
    p("DWPT", "Dew Point [C]", y)
    p("MIXR", "Mixing Ratio", y)
    p("DRCT", "Wind Dir.", y)
    p("SKNT", "Speed [knots]", y)
}

if (!interactive()) dev.off()
```

**Plots with height on y axis**

![atm_1](https://user-images.githubusercontent.com/99469/211223300-d317c707-60f9-44dc-85a0-a87e176a4707.png)

**Plots with pressure on y axis**

![atm_2](https://user-images.githubusercontent.com/99469/211223298-5ab37d19-4dac-4ee6-a7a6-38cf6fd39ec2.png)

**Comment by AnnieHow** [comment]
@dankelley I would say absolutely add this in! When I did field work we always set up wind instruments near our study site, data like this is super useful.

**Comment by dankelley** [comment]
Cool, will do, perhaps this aft.  I'll make a PR and let you do the merging of that, since you're names as the maintainer in the DESCRIPTION file.

**Comment by dankelley** [comment]
Done in "main" commit d928073f7d0135243c414d765203bada99b70742.

@AnnieHow in the example, I am using a temporary destdir.  See the commit notes for 84e3f85c743c8f2d503d6fa7f110090404a31eea ... I think we need to use a temporary destdir for all downloads, because otherwise CRAN will reject it.  We may as well be doing the right thing now, instead of planning to figure things out later.  The way to do that is to always follow a "build" with a "test" and then a "check", and not to push to GH until all are clear.
