### ISSUE TITLE
should dod.download(), etc, have an 'age' parameter?

### ISSUE THREAD

**Issue by dankelley** [AnnieHow/dod#45]
We do this in `argoFloats`.  The idea is that we reuse an existing file, if it is already downloaded, so long as the file is younger than the specified age.  This is very helpful for infrequently changed data (e.g. most CTD data, topographical data) etc.

Oh, and that scheme is used in `oce` as well as in `argoFloats`, so I'm not really suggesting something radical.

The `age` parameter can be defaulted to a value that ensures that the old behaviour is retained.

I wonder what @AnnieHow and @j-harbin think about this idea.  Let's have a vote, with -1 meaning to not add the parameter, +1 meaning to add it, and any value in between those limits signalling the strength of conviction.  The advantage of this voting scheme is that the decision is made simply by summing votes and seeing if the result is positive or negative.

Since this can be made backward-compatible, **I vote +1**.

PS. I came up with this idea whilst using `dod.download()` to download some drifter (not argo) data.  I thought it was a bug that it kept re-downloading data (a slow operation) as I ran and reran my code during writing.

**Comment by j-harbin** [comment]
I also give this a +1 vote. 

I see you mention that this is useful for infrequently changed data. This reminded me that we also added an `age="latest"` argument into `getProfiles()` in `argoFloats` (which DOES have frequently changing data).

The idea is that we would get the file if A) The file doesn't already exist or B) The file does exist and the date it was created is OLDER than the date_update in the index. (see https://github.com/ArgoCanada/argoFloats/pull/573)

The date_update may be specific to Argo data, but it is worth checking to see if other frequently changed datasets have something of this nature.

**Comment by dankelley** [comment]
Datasets usually don't have an index, actually.  We are lucky on Argo data (and some other data that `dod` handles, like the BBMP data).

For fun, here's a graph of the drifter data I downloaded.  The red dot is the starting point (where the drifter was chucked into the ocean).  See the nice simple currents?  Nope?  Well, the ocean is a mess!  But, ooooh, there are some very neat things in there.  If I were teaching this term...

![01](https://user-images.githubusercontent.com/99469/212897557-99cd46f9-98ff-4fe5-bb01-dea1d3127172.png)

**Comment by AnnieHow** [comment]
**I vote +1**. No one wants doubles!

To clarify is the age parameter saying only download from where I'm telling you to if  you've already checked that I don't have the same file downloaded within `age=x` amount of time?

**Comment by dankelley** [comment]
Let's determine the wording in the issue.  I propose (and ask for edits to)

```
#' @param age a numerical value indicating a time interval, in days.  If the file
#' to be downloaded from the server already exists locally, and was created
#' is less than `age` days in the past, it will not be downloaded.  
#' Setting `age=0` (which is the default) will force a download.
```

**Comment by AnnieHow** [comment]
I think that sounds great!

**Comment by j-harbin** [comment]
I see it's similar to what we have in `argoFloats` and we've never had a problem, so I think it looks good!

**Comment by dankelley** [comment]
Returning to this a few months later, because I want to use it :-)

I'll code it, doing `dod.ctd.bbmp()` first, because that's what I want today.

**Comment by dankelley** [comment]
I've got this working now, as shown below.  I'll close the issue once I rebuild and retest, etc.  Oh, and if/when the power comes back on.  Sunny, calm day in Halifax -- I'm sure NSPower has a clever excuse for this one.

```R
> library(oce)
library(dod)
year <- 2022
debug <- 2 # turn on debugging, two levels deep
age <- 7 # don't bother re-downloading if local version is under 7 day sold
Loading required package: gsw
> library(dod)
> year <- 2022
> debug <- 2 # turn on debugging, two levels deep
> age <- 7 # don't bother re-downloading if local version is under 7 day sold
> indexFile <- dod.ctd("BBMP", year=year, index=TRUE, age=7, debug=debug)
  dod.ctd.bbmp(year=2022, ID=NULL, index=TRUE, file="", destdir=".", age=7, debug=2)
  {
    dod.download(url="ftp://ftp.dfo-mpo.gc.ca/BIOWebMaster/BBMP/ODF/2022/2022667ODFSUMMARY.tsv", file="20
22667ODFSUMMARY.tsv", destdir=".", age=7, silent=TRUE, debug=1)
    {
        existing file is 1.44 hours so it will not be downloaded
    } # dod.download()
  } dod.ctd.bbmp()
> indexFile <- dod.ctd("BBMP", year=year, index=TRUE, debug=debug)
  dod.ctd.bbmp(year=2022, ID=NULL, index=TRUE, file="", destdir=".", age=0, debug=2)
  {
    dod.download(url="ftp://ftp.dfo-mpo.gc.ca/BIOWebMaster/BBMP/ODF/2022/2022667ODFSUMMARY.tsv", file="20
22667ODFSUMMARY.tsv", destdir=".", age=0, silent=TRUE, debug=1)
    {
      existing file age is 1.44 hours old, so must download a newer version
    } # dod.download()
  } dod.ctd.bbmp()
```

**Comment by dankelley** [comment]
commit 75eee008b056f2bc04d6822c88795232954db834
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Apr 21 09:53:13 2023 -0300

    add age parameter to all downloading functions
    
    Also, clean up debugging code for the one I was using today,
    dod.ctd.bbmp().  The text was quite messy before, so I took some time to
    format it more clearly, with reduced duplication and verbosity.
