### ISSUE TITLE
dod.met.sounding() is failing

### ISSUE THREAD

**Issue by dankelley** [AnnieHow/dod#47]
```R
 > ### Name: dod.met.sounding
  > ### Title: Download sounding data
  > ### Aliases: dod.met.sounding
  > 
  > ### ** Examples
  > 
  > # Download
  > tempdir <- tempfile()
  > dir.create(tempdir)
  > station <- "73110"
  > year <- "2023"
  > month <- "01"
  > day <- "08"
  > file <- dod.met.sounding(station, year=year, month=month, day=day, destdir=tempdir)
  Error in dod.download(url, destdir = destdir, file = file, age = age,  : 
    An error occured when trying to download "https://weather.uwyo.edu/cgi-bin/sounding?region=naconf&TYPE=TEXT%3ALIST&YEAR=2023&MONTH=01&FROM=0812&TO=0812&STNM=73110"
  Calls: dod.met.sounding -> dod.download
  Execution halted
```

**Comment by dankelley** [comment]
Actually, this might just be a 'server too busy' error so I'll try again early morning, my time, when Americans are not likely to be using this.

**Comment by dankelley** [comment]
I altered the docs for the function, to not run the example.  See commit notes for commit
f95a6121d3a56fa02e5d5e119fe6f5a991ea3586 of branch "main".

**Comment by j-harbin** [comment]
Love to see the continued development to this package!

**Comment by dankelley** [comment]
Yeah, I'm mainly working on `dod.amsr()` today because I noticed yesterday that it was failing.  They changed the remote directory structure.  And the files are also different -- very very different.  I want them for some work I'm doing right now, and certainly for classes in September.  For fun, below is a recent view of the world.  I could look at pictures like this all day.  But, boy oh boy, it is tricky coding `dod.amsr()` to grab the images.

![amsr_01](https://github.com/AnnieHow/dod/assets/99469/b766ba8c-8471-4fef-bcdd-8653b59f1e01)
