### ISSUE TITLE
Create error message if user provides incorrect item name

### ISSUE THREAD

**Issue by j-harbin** [AnnieHow/dod#6]
Right now, in `dod.ctd()`, the user has the option to provide `item="index"` to obtain a data frame that contains a list of file names and the time. They can then take the list of file names and do a further step similar to the following:

`dod.ctd("BBMP", 2005, "CTD_BCD2005667_1_1_DN.ODF")`

We need to print an error message if the user does not provide a correct file name.

**Comment by dankelley** [comment]
@j-harbin and maybe @AnnieHow -- feel like a Z to chat about this?  I'm avail.  (We should not put zoom links here on GH.)

**Comment by j-harbin** [comment]
Fixed after a Z with AH and DK in commit 29a639e11cc3df97f488d18a74b910d596d382c2 . See screen shot below
![Screen Shot 2022-10-31 at 7 54 39 AM](https://user-images.githubusercontent.com/58750538/198992410-2eabf0c5-150b-4a03-960c-4d276cb49453.png)
